{{- if and .Values.tailscale.authKey (not .Values.tailscale.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-darm-agents-ts
  labels: {{- include "darm-agents.labels" . | nindent 4 }}
type: Opaque
stringData:
  TS_AUTHKEY: {{ .Values.tailscale.authKey | quote }}
{{- end }}
{{- if and .Values.auth.token (not .Values.auth.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-darm-agents-auth
  labels: {{- include "darm-agents.labels" . | nindent 4 }}
type: Opaque
stringData:
  DARM_TOKEN: {{ .Values.auth.token | quote }}
{{- end }}
