apiVersion: v1
kind: Secret
metadata:
  name: {{ include "darm-ann.fullname" . }}-tokens
  labels: {{- include "darm-ann.labels" . | nindent 4 }}
type: Opaque
stringData:
  DARM_TOKENS: {{ .Values.tokens.api | quote }}
  DARM_CLUSTER_TOKEN: {{ .Values.tokens.cluster | quote }}
