{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "darm-ann.fullname" . }}
  labels:
    {{- include "darm-ann.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels: {{- include "darm-ann.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /darm/metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
