apiVersion: v1
kind: Service
metadata:
  name: {{ include "darm-ann.fullname" . }}-headless
  labels: {{- include "darm-ann.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector: {{- include "darm-ann.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "darm-ann.fullname" . }}
  labels: {{- include "darm-ann.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "darm-ann.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
